### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by cmancuyas** [maelstrom-cms/toolkit#1]
Cannot Add new category
get_class() expects parameter 1 to be object, null given
**To Reproduce**
1. Follow the instructions in installing
2. Go to settings->categories then click "Create Category"
Fill up the fields then press save

**Comment by OwenMelbz** [comment]
Hi @yashiro089 can you zip or upload your code base for me to look at please?

**Comment by OwenMelbz** [comment]
@yashiro089 do you still have a problem? I'll close this issue if you no longer need help.

It's worth noting that a couple of patches have been released in the last few days that are worth getting.

Thanks
