### ISSUE TITLE
How to change language in maelstrom-cms ant design

### ISSUE THREAD

**Issue by krvipsoft** [maelstrom-cms/toolkit#12]
want to change the language, now I don’t know what to do? Can you help me?
![image](https://user-images.githubusercontent.com/42866392/90502231-73a1b200-e188-11ea-8498-710633ceefb3.png)

**Comment by OwenMelbz** [comment]
Hi, it's not "built" for multi lingual, the documentation states this.

You can follow the Ant Design documentation for changing localities, and Laravel documentation on overriding classes/languages/templates.

As this isn't a bug, I'll close the issue but can respond if needed :)
