### ISSUE TITLE
[Support] Mass-deletion fails

### ISSUE THREAD

**Issue by andrewminion-luminfire** [maelstrom-cms/toolkit#2]
**Describe the bug**
Mass-deleting objects fails, and instead tries to create objects.

**To Reproduce**
1. Set up a basic Maelstrom project as described in the documentation.
1. Create a migration/model for pages with a non-nullable `name` field.
2 Add multiple pages.
3. Go to the pages index webview.
4. Select multiple pages using the checkboxes.
5. Scroll to the bottom; in the “Bulk Actions” dropdown, choose “Delete selected” and hit the thumbs up button.
6. See an error about MySQL `name` field not having a default value—rather than deleting the pages, it’s trying to create a new page and failing because the database isn’t allowing a null value in the `name` field.

**Expected behavior**
I expected the selected pages to be deleted, not an attempt to create a new page.

**Screenshots**
See error stack: https://flareapp.io/share/67O9Nkmr#F55

**Comment by OwenMelbz** [comment]
Hi,

Have you followed the instructions for setting up bulk actions!?

https://www.maelstrom-cms.com/advance/bulk-actions.html

The issue your facing is normally when you don’t have a route defined which handles the bulk actions, which then falls back to the POST method which maps to the create.

You can also check php artisan route::list to see if the bulk route is registered

**Comment by andrewminion-luminfire** [comment]
Ah…I totally missed that section. Thanks—that did the trick.
