### ISSUE TITLE
[Question] Media Manager doesnt upload images and returns a SQL ERROR

### ISSUE THREAD

**Issue by KarimFekry8** [maelstrom-cms/toolkit#8]
I've been having a problem using media manager as whenever I try to upload an image it throws a SQL error saying that the image doesn't have a default value
![Screenshot (14)](https://user-images.githubusercontent.com/47244510/78454945-ae082800-769b-11ea-8abc-6d63d542c918.png)

**Comment by OwenMelbz** [comment]
Hi,

This looks like your database schema isn't set up to take an empty `image` column.

I'd suggest checking the `$fillable` property on your admin interests model to check you've allowed the `image` column to be filled.

As this isn't a maelstrom bug - I'll close the ticket to keep things tidy, but will continue to respond if needed.
