### ISSUE TITLE
maelstrom.form-options 404

### ISSUE THREAD

**Issue by kylethomas-dev** [maelstrom-cms/toolkit#9]
I am receiving a 404 when using maelstrom.form-options. All setup as according to the documentation. I have copied the code below for reference. Any help would be greatly appreciated.

Thanks,

Kyle

```
'form_options' => [
        /*
         * If you want the automatic form options route to register,
         * set to false if you want to disable it or provide your own routes.
         */
        'enabled' => true,

        /*
         * If your using a custom auth guard, you can define it here.
         */
        'guard' => null,

        /*
         * If you need to protect this endpoint at route level or anything else
         * you can provide some middleware, which can abort(401) the request.
         */
        'middleware' => ['web'],

        /*
         * These form options will be included in the AJAX endpoint.
         * We just need to know the "name" of the set, then which model
         * it is you're wanting to return values of, any applied scopes
         * where the value field should draw from and which field should be the
         * name/label field.
         *
         * 'categories' => [
         *     'model' => App\Category::class,
         *     'scopes' => ['customScope'],
         *     'value' => 'id',
         *     'label' => 'name',
         * ],
         *
         */
        'models' => [
            'categories' => [
                'model' => App\Category::class,
                'value' => 'id',
                'label' => 'name',
            ],
        ],
    ],

```
<img width="833" alt="Screen Shot 2020-04-09 at 9 22 28 pm" src="https://user-images.githubusercontent.com/55139370/78890051-44778780-7aa8-11ea-96c0-bb3a06244b39.png">
<img width="1236" alt="Screen Shot 2020-04-09 at 9 23 20 pm" src="https://user-images.githubusercontent.com/55139370/78890116-6113bf80-7aa8-11ea-8443-db183aae070f.png">

`

**Comment by OwenMelbz** [comment]
Hi,

Can you share the output of `php artisan route:list` please to see if the route got registered at all?

Thanks

**Comment by kylethomas-dev** [comment]
Hi Owen,

I have inserted the output as an attachment.
<img width="897" alt="Screen Shot 2020-04-14 at 7 46 09 am" src="https://user-images.githubusercontent.com/55139370/79164288-1c7b8180-7e24-11ea-98e9-aae580d4c707.png">
Thanks for your help.

**Comment by OwenMelbz** [comment]
I can see towards the bottom of the list that the route is registered.

So we’d need to figure out why you cannot actually access it.

The first thing I’ve noticed that “might” make a difference is that you’ve got some “auth” middleware registered on many of your routes, but not on the form options config.

Could you try adding the auth middleware to the form options config as well please.

Also can you confirm you do have a model called “App\Category” ??

Thanks

**Comment by kylethomas-dev** [comment]
Sorry, still no luck.
I have followed all setup instructions to the letter and have so far had no success with the maelstrom-api/form-options. I have tried registering other models via maselstrom.php and still no luck.

**Comment by kylethomas-dev** [comment]
Hi Owen,

Attached is another screenshot of my current issue. When I go to add a new category from my Posts page I get the error and no field is visible. Thanks again for your help.
<img width="1412" alt="Screen Shot 2020-04-14 at 9 29 30 pm" src="https://user-images.githubusercontent.com/55139370/79220334-22f71100-7e97-11ea-85e1-94cffeec105c.png">

**Comment by OwenMelbz** [comment]
Hi,

To try get through this, you're going to need to try to do a little digging in the code I'm afraid.

This is the controller that gets loaded: https://github.com/maelstrom-cms/toolkit/blob/master/src/Http/Controllers/FormOptionsController.php

You can find it in your `vendor/maelstrom-cms/toolkit/src/Http/Controllers/FormOptionsController.php`

We need to put some debug messages in here to see where it gets to

On [line 38](https://github.com/maelstrom-cms/toolkit/blob/master/src/Http/Controllers/FormOptionsController.php#L38) can you replace it with `exit('not enabled');`

On [line 59](https://github.com/maelstrom-cms/toolkit/blob/master/src/Http/Controllers/FormOptionsController.php#L59) can you replace it with `exit($type . ' not found');`

These are the only 2 places in the controller that return 404s

Now once you've made those changes and you visit the URL, what do you get?

If neither of these execute, then it seems something else in the application might be affecting them.

It might be that you'd need to invite me to the GIT repo so I can take a look as I don't believe theres a bug in the system as we're using this in multiple places all fine, so its most likely a conflict or configuration issue that we need to track down.

Thanks

**Comment by kylethomas-dev** [comment]
Hi,
Made the amendments and I receive the 'categories not found' message, (line 59 change).

Thanks

**Comment by OwenMelbz** [comment]
Right okay! Getting somewhere.

That means that it is not reading your config to find the `categories` key.

from within your project, in terminal, can you run each of the following commands one-by-one.

```
php artisan tinker
dd(config('maelstrom.form_options.models'));
exit;
```

And share the results please

**Comment by kylethomas-dev** [comment]
Hi, 

Results attached in a screenshot attached. Seems like the form_options.models is empty
<img width="407" alt="Screen Shot 2020-04-14 at 10 17 52 pm" src="https://user-images.githubusercontent.com/55139370/79224054-d3681380-7e9d-11ea-94bc-b18b11666132.png">


Thanks,

**Comment by OwenMelbz** [comment]
Hi,

Can you share the contents of your `config/maelstrom.php` to see how you've configured the models then please?

**Comment by kylethomas-dev** [comment]
```php
return [
    /*
     * Displays in the logo area.
     */
    'title' => 'Title',

    /*
     * The root path of your control panel.
     */
    'path' => '/admin',

    /*
     * This will be prepended to the start of all breadcrumbs.
     */
    'breadcrumb' => [
        [
            'label' => 'Admin',
            'url' => '/admin'
        ]
    ],

    /*
     * You can set some base sidebar items here, nothing fancy, however
     * we recommend defining this somewhere else so you can use things
     * such as the route() helper, we just need to globally expose a variable
     * called $maelstrom_sidebar which we can do inside the AppServiceProviders boot method
     *
     * e.g. View::share('maelstrom_sidebar', [ ...items ])
     */
    'sidebar' => [
        [
            'id' => 'dashboard',
            'label' => 'Dashboard',
            'url' => '/admin',
            'icon' => 'radar-chart',
        ]
    ],

    /*
     * "light" or "dark" - This gets passed to ant design where possible.
     */
    'theme' => 'dark',

    /*
     * Where does your asset pipeline output our JS?
     * (relative to the public folder)
     */
    'core_js_path' => 'js/maelstrom.js',

    /*
     * Where does your asset pipeline output our CSS?
     * (relative to the public folder)
     */
    'core_css_path' => '/css/maelstrom.css',

    /*
     * Will include custom css files after maelstrom.css on every page.
     */
    'custom_css' => [],

    /*
     * Will include custom js files after maelstrom.js on every page.
     *
     * If you want automatic cache busting AND config caching
     * You'll need to push to the stack `footer_after` or
     * publish the `maelstrom:partials/footer-scripts.blade.php`
     * and use the `mix()` helper in there.
     */
    'custom_js' => [],

    /*
     * Although we use the IoC container to allow you to overwrite
     * which panel we load, you can also define your custom root panel here.
     */
    'panel' => \Maelstrom\Panel::class,

    /*
     * If you need some basic authentication, we've got some bits for you.
     * Use as much or as little as you need.
     */
    'auth' => [
        /*
         * If you want the built in authentication features,
         * set to false if you want to disable it.
         */
        'enabled' => true,

        /*
         * If your using a custom auth guard, you can define it here.
         */
        'guard' => null,

        /*
         * If you need to protect this endpoint at route level or anything else
         * you can provide some middleware, which can abort(401) the request.
         */
        'middleware' => ['web'],

        /*
         * We use the current user in "some" places - mostly on the
         * "edit my account" page, if you use the built in controller
         * then you can change the model here.
         */
        'model' => \App\User::class,
    ],

    /*
     * We provide a form of nested resources, that allow you to
     * pick related entities e.g. categories, we have a little
     * automated system which can help you with this which can
     * be configured below.
     */
    'form_options' => [
        /*
         * If you want the automatic form options route to register,
         * set to false if you want to disable it or provide your own routes.
         */
        'enabled' => true,

        /*
         * If your using a custom auth guard, you can define it here.
         */
        'guard' => null,

        /*
         * If you need to protect this endpoint at route level or anything else
         * you can provide some middleware, which can abort(401) the request.
         */
        'middleware' => ['web'],

        /*
         * These form options will be included in the AJAX endpoint.
         * We just need to know the "name" of the set, then which model
         * it is you're wanting to return values of, any applied scopes
         * where the value field should draw from and which field should be the
         * name/label field.                 
         */
        'models' => [
            'categories' => [
                'model' => App\Category::class,
                'value' => 'id',
                'label' => 'name',
            ],
        ],
    ],

    /*
     * Our media manager is a simple tool to attach
     * single or multiple media items to another entity,
     * it provides back the ID of the related media
     * which you can handle however you like, the options
     * are listed below.
     */
    'media_manager' => [
        /*
         * If you want the automatic form options route to register,
         * set to false if you want to disable it or provide your own routes.
         */
        'enabled' => true,

        /*
         * If your using a custom auth guard, you can define it here.
         */
        'guard' => null,

        /*
         * If you need to protect this endpoint at route level or anything else
         * you can provide some middleware, which can abort(401) the request.
         */
        'middleware' => ['web'],

        /*
         * Provide the disk from filesystems.php which will be
         * used to store the uploaded media.
         */
        'disk' => 'public',

        /*
         * If you need to inject a custom media class, you can do so - however make sure it
         * extends our base class, or copies the methods across.
         */
        'model' => \Maelstrom\Models\Media::class,

        /*
         * A list of accepted mime-types for the media uploader.
         * We use the symfony mime type detection for this, which
         * isn't always accurate, so be careful.
         */
        'mime_types' => [
            'image/svg',
            'image/png',
            'image/jpeg',
            'application/pdf',
        ],

        /*
         * What dimensions should we make the thumbnails of uploaded assets?
         */
        'thumbnails' => [
            'width' => 300,
            'height' => 300,
        ],
    ]
];
```

**Comment by OwenMelbz** [comment]
Hi,

Are you sure thats the whole file? it seems to be missing at least the `<?php` tags at the top to say it's got PHP code in it.

I've just copied the config you've provided into a working project, and debugged the `config('maelstrom.form_options.models')` and it returns me the `categories`.

I'm wondering if you've turned on config caching and maybe not cleared it by running `php artisan config:clear` after making changes?

If that doesn't work, then the only last option is that there is something particular with what you've done somewhere that is conflicting.

Running the official `config()` helper says you've not got a valid config file, that will be the problem. What you'll need to try and figure out is why you do not have a valid config, there must be something somewhere in your code that means laravel cannot read the config.

I can't really help you with that specifically, but that is what needs to be identified - once you've got the config to load, then we can continue if theres still a problem

**Comment by kylethomas-dev** [comment]
Hi Owen,

Running php artisan config:clear fixed my issue!
Thank you so much for your help with this.

Regards,

Kyle

**Comment by OwenMelbz** [comment]
Hi,

No worries, for future reference, you probably should *never* run `php artisan config:cache` in development as it will cause issues like this, I'm not sure what the requirement was - but effectively you cached an old config and didnt clear the cache when you made config changes.
